import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router";
import ExecutiveFilters from "../../components/executive/ExecutiveFilters";
import { ExecutiveError, ExecutiveLoading } from "../../components/executive/ExecutiveState";
import { asOf, money, percent } from "../../components/executive/executiveFormat";
import { getExecutiveComponent, type ExecutiveFilters as Filters } from "../../services/executive";
import type { ComponentDetailResponse } from "../../types/executive";

export default function ComponentComparisonPage() {
  const { componentId = "" } = useParams();
  const [filters, setFilters] = useState<Filters>({ period: "FY26", scope: "enterprise" });
  const [detail, setDetail] = useState<ComponentDetailResponse | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { let active = true; getExecutiveComponent(componentId, filters).then(result => { if (active) { setDetail(result); setError(""); } }).catch(requestError => active && setError(requestError instanceof Error ? requestError.message : "Component data could not be loaded")); return () => { active = false; }; }, [componentId, filters]);
  const supplierGap = Number(detail?.commercial_delta ?? 0);
  const action = useMemo(() => detail ? supplierGap > 0 ? [
    `Renegotiate ${detail.current_supplier ?? "the primary supplier"} against the qualified benchmark.`,
    `Validate ${detail.benchmark_supplier ?? "the lowest-cost alternate"} for quality, capacity and delivery.`,
    `Model the ${money(Number(detail.annual_tariff_impact))} annual tariff exposure before the next decision gate.`,
  ] : [
    `Protect the current commercial position with ${detail.current_supplier ?? "the primary supplier"}.`,
    `Use ${detail.benchmark_supplier ?? "the alternate source"} for resilience only after a total-cost review.`,
    `Focus negotiation on the ${money(Number(detail.annual_tariff_impact))} annual tariff exposure.`,
  ] : [], [detail, supplierGap]);
  return <main className="executive-page component-page">{error ? <ExecutiveError message={error}/> : !detail ? <ExecutiveLoading/> : <>
    <div className="executive-heading"><div><span className="eyebrow">COMPONENT COMPARISON · {detail.component_id}</span><h1>{detail.component_name} opportunity brief</h1><p>Supplier, volume and tariff intelligence for the leading component action.</p></div><div className="component-heading-side"><span className="component-confidence">● {percent(Number(detail.confidence_score) * 100)} confidence</span><ExecutiveFilters value={filters} onChange={setFilters} asOfDate={detail.as_of_date}/></div></div>
    <section className="component-kpis"><div><small>ANNUAL OPPORTUNITY</small><strong>{money(Number(detail.annual_opportunity))}</strong><span>{detail.opportunity_count} opportunities</span></div><div><small>SUPPLIER DELTA</small><strong>{detail.supplier_delta_percent == null ? "—" : `${percent(Math.abs(Number(detail.supplier_delta_percent)))} ${supplierGap > 0 ? "above" : "below"}`}</strong><span>{detail.current_supplier ?? "Primary"} vs alternate</span></div><div><small>VOLUME CHANGE</small><strong>{percent(Number(detail.volume_change_percent))}</strong><span>{Number(detail.annual_volume).toLocaleString()} attributed units</span></div><div><small>TARIFF IMPACT</small><strong>{money(Number(detail.annual_tariff_impact))}</strong><span>{money(Number(detail.tariff_per_unit), false)} per unit · HS {detail.hs_code}</span></div></section>
    <section className="component-brief-layout"><div className="component-evidence"><span className="eyebrow">COMMERCIAL EVIDENCE</span><h2>{supplierGap > 0 ? "Supplier economics are amplifying" : "Current sourcing partly offsets"} the {detail.lead_plant} component gap</h2><p>The current primary source is compared with the lowest-cost qualified alternate in the seeded supplier network. Financial measures use the latest valid evidence as of {asOf(detail.as_of_date)}.</p><dl><div><dt>Current supplier</dt><dd>{detail.current_supplier ?? "Not available"}</dd></div><div><dt>Qualified alternate</dt><dd>{detail.benchmark_supplier ?? "Not available"}</dd></div><div><dt>Current unit cost</dt><dd>{detail.current_supplier_unit_cost == null ? "—" : money(Number(detail.current_supplier_unit_cost), false)}</dd></div><div><dt>Alternate unit cost</dt><dd>{detail.benchmark_supplier_unit_cost == null ? "—" : money(Number(detail.benchmark_supplier_unit_cost), false)}</dd></div><div><dt>Commercial delta</dt><dd className={supplierGap > 0 ? "metric-risk" : "metric-good"}>{detail.commercial_delta == null ? "—" : `${money(Number(detail.commercial_delta), false)} / unit`}</dd></div><div><dt>Duty rate vs peer</dt><dd>{percent(Number(detail.duty_rate))} vs {percent(Number(detail.peer_duty_rate))}</dd></div></dl></div><aside className="component-action"><span>✦</span><small>RECOMMENDED ACTION</small><h2>{supplierGap > 0 ? "Renegotiate and validate alternate sourcing" : "Protect price and reduce tariff exposure"}</h2><ol>{action.map(item => <li key={item}>{item}</li>)}</ol><Link to={`/executive/opportunities/${detail.lead_opportunity_id}`}>Open action brief</Link></aside></section>
    <section className="component-table-layout"><div className="executive-table-panel"><div className="section-title"><div><span className="eyebrow">SUPPLIER COMPARISON</span><h2>Qualified source economics</h2></div></div><div className="table-wrap"><table><thead><tr><th>Supplier</th><th>Unit cost</th><th>Annual spend</th><th>Quality</th><th>Delivery</th></tr></thead><tbody>{detail.suppliers.map(supplier => <tr key={supplier.supplier_id}><td><strong>{supplier.supplier_name}</strong><small>{supplier.country}{supplier.is_primary_supplier ? " · Current primary" : ""}</small></td><td>{money(Number(supplier.unit_cost), false)}</td><td>{money(Number(supplier.annual_spend))}</td><td>{Number(supplier.quality_score).toFixed(1)} / 5</td><td>{Number(supplier.delivery_score).toFixed(1)} / 5</td></tr>)}</tbody></table></div></div><aside className="component-products"><span className="eyebrow">PRODUCT FIT</span><h2>Compatible equipment</h2><p>This component is linked to {detail.products.length} seeded equipment models.</p>{detail.products.map(product => <Link key={product.product_id} to={`/executive/products/${product.product_id}`}><span>{product.product_name}</span><b>View →</b></Link>)}</aside></section>
  </>}</main>;
}
